In [55]:
import pandas as pd   
import numpy as np

In [56]:
dataset=pd.read_csv('data.csv',lineterminator='\n')
dataset.head(4)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...

In [57]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   object
 1   Title              9827 non-null   object
 2   Overview           9827 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   object
 7   Genre              9827 non-null   object
 8   Poster_Url         9827 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 691.1+ KB

In [58]:
dataset['Release_Date']=pd.to_datetime(dataset['Release_Date'])
print(dataset['Release_Date'].dtypes)

datetime64[ns]

In [59]:
dataset['Release_Date']=pd.DatetimeIndex(dataset['Release_Date']).year

In [60]:
dataset.duplicated().sum()

0

In [61]:
col=['Overview','Original_Language','Poster_Url']
dataset.drop(col,axis=1,inplace=True)
dataset.columns

Index(['Release_Date', 'Title', 'Popularity', 'Vote_Count', 'Vote_Average',
       'Genre'],
      dtype='object')

In [62]:
dataset.head(5)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,6.3,Thriller
3,2021,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"

In [63]:
def categorize_col(datasett,col,lab):
    edes=[
        datasett[col].describe()['min'],
        datasett[col].describe()['25%'],
        dataset[col].describe()['50%'],
        datasett[col].describe()['75%'],
        datasett[col].describe()['max'],
        ]
    
    datasett[col]=pd.cut(datasett[col],edes,labels=lab,duplicates='drop')
    return datasett

In [64]:
labb=['not_good','below_avg','avg','good']
categorize_col(dataset,'Vote_Average',labb)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,good,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,good,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,below_avg,Thriller
3,2021,Encanto,2402.201,5076,good,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,avg,"Action, Adventure, Thriller, War"
...,...,...,...,...,...,...
9822,1973,Badlands,13.357,896,good,"Drama, Crime"
9823,2020,Violent Delights,13.356,8,not_good,Horror
9824,2016,The Offering,13.355,94,not_good,"Mystery, Thriller, Horror"
9825,2021,The United States vs. Billie Holiday,13.354,152,avg,"Music, Drama, History"
9826,1984,Threads,13.354,186,good,"War, Drama, Science Fiction"

In [65]:
dataset['Vote_Average'].unique()

['good', 'below_avg', 'avg', 'not_good', NaN]
Categories (4, object): ['not_good' < 'below_avg' < 'avg' < 'good']

In [66]:
dataset['Vote_Average'].value_counts()

Vote_Average
not_good     2467
good         2450
avg          2412
below_avg    2398
Name: count, dtype: int64

In [67]:
dataset.isnull().sum()
dataset.dropna(inplace=True)

In [68]:
dataset['Genre']=dataset['Genre'].str.split(', ')
dataset=dataset.explode('Genre').reset_index(drop=True)

In [69]:
dataset.head(4)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,good,Action
1,2021,Spider-Man: No Way Home,5083.954,8940,good,Adventure
2,2021,Spider-Man: No Way Home,5083.954,8940,good,Science Fiction
3,2022,The Batman,3827.658,1151,good,Crime

In [70]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25552 entries, 0 to 25551
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Release_Date  25552 non-null  int32
 1   Title         25552 non-null  object
 2   Popularity    25552 non-null  float64
 3   Vote_Count    25552 non-null  int64
 4   Vote_Average  25552 non-null  category
 5   Genre         25552 non-null  object
dtypes: category(1), float64(1), int32(1), int64(1), object(2)
memory usage: 923.6+ KB

In [71]:
dataset.nunique()

Release_Date     100
Title           9415
Popularity      8088
Vote_Count      3265
Vote_Average       4
Genre             19
dtype: int64

In [72]:
dataset.to_csv('data_clean.csv',index=False)